### ISSUE TITLE
Toolbar not showing up

### ISSUE THREAD

**Issue by tiferrei** [suda/toolbar-main#12]
I'm sorry if this is a dumb question but I've installed the package and nothing shows up, what am I doing wrong?
<img width="1280" alt="screen shot 2016-02-04 at 23 06 32" src="https://cloud.githubusercontent.com/assets/8849915/12832756/0417f980-cb94-11e5-9bf0-8959c9c9c593.png">
<img width="1280" alt="screen shot 2016-02-04 at 23 06 52" src="https://cloud.githubusercontent.com/assets/8849915/12832757/04386206-cb94-11e5-9da6-dd5ece79bf15.png">

**Comment by jerone** [comment]
First have you installed the [tool-bar](https://atom.io/packages/tool-bar) package?
If yes, did you have the [tool-bar visible](https://github.com/suda/tool-bar#visiblity)?
If yes, did you get any errors in the developer console?
