### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by web-snake** [suda/toolbar-main#14]
Sorry for the lack of detail in the title. I'm not an atom extension developer, I'm a developer that uses atom extensions. There are no instructions and it simply does nothing.
After digging into your code I found the problem, but your extension will not be accessible to people trying to use your extension as a black box until you clear up the mistake in the may you reported your dependencies.
You said that your awesome-toolbar requires toolbar
Unfortunately there is no such dependency in the atom extension search.
Apparently there may be slight differences in the dependecies required in the code and what appears in the Atom Install Packages Search. Only Atom developers will have any idea that such a deprepency exists.
If you search for "toolbar" you will be given several choices like atom-toolbar and toolbar-basic
One might assume that when you incorrectly said "toolbar" you meant atom-toolbar or even basic toolbar.
But those don't work and your toolbar does absolutley nothing unless you give people the correct dependency, which is none of the above
The correct dependency is "toolbar-main"
This work as expected when you install the correct dependency and people will do that only when its listed correctly.

**Comment by jerone** [comment]
As seen in the readme, this package requires the [tool-bar](https://atom.io/packages/tool-bar) package, which [should](https://github.com/suda/toolbar-main/blob/master/lib/tool-bar-main.coffee#L3) be installed if that dependency was installed before. Of course a restart of Atom is required to make the tool-bar attach to the view. 

If you believe the readme is insufficient, please send a [PR](https://github.com/suda/toolbar-main/edit/master/README.md) and I'll review it.
