### ISSUE TITLE
Adding tree view toggle

### ISSUE THREAD

**Issue by jdsimcoe** [suda/toolbar-main#6]
How would i add a toggle button for tree view with toolbar. Is this something you'd consider adding to `toolbar-main`?

**Comment by jerone** [comment]
Have a look at the [flex-tool-bar](https://atom.io/packages/flex-tool-bar), which allows you to define your own buttons.

If you want it to be part of this package, send us a PR and we'll consider it.

**Comment by jdsimcoe** [comment]
Thanks @jerone I saw the `flex-tool-bar` and that is great but it doesn't allow for logic like you have for Dev Mode, etc. Also do you know if it is even possible in the Atom API to grab the repository's public URL. That would be cool to map to an Octocat icon.

**Comment by jerone** [comment]
[**@jdsimcoe**](https://github.com/jdsimcoe) commented on [28 jun. 2015 01:51 CEST](https://github.com/suda/toolbar-main/issues/6#issuecomment-116166251 "2015-06-27T23:51:27Z - Replied by Github Comment Enhancer"):
> Thanks @jerone I saw the `flex-tool-bar` and that is great but it doesn't allow for logic like you have for Dev Mode, etc. 

Dev mode is supported by flex-tool-bar ([I even added it](https://github.com/cakecatz/flex-toolbar/pull/7) :) ): `"mode": "dev"`

[**@jdsimcoe**](https://github.com/jdsimcoe) commented on [28 jun. 2015 01:51 CEST](https://github.com/suda/toolbar-main/issues/6#issuecomment-116166251 "2015-06-27T23:51:27Z - Replied by Github Comment Enhancer"):
> Also do you know if it is even possible in the Atom API to grab the repository's public URL. That would be cool to map to an Octocat icon.

Just use the commands from the internal package [open-on-github](https://github.com/atom/open-on-github): `open-on-github:repository`.

**Comment by jdsimcoe** [comment]
Thanks @jerone. Nice!
