### ISSUE TITLE
Doesn't work on Windows 8

### ISSUE THREAD

**Issue by nbpalomino** [suda/toolbar-main#7]
Just that...

Recently installed from **apm install tool-bar-main** and doesn't work.

**Comment by nbpalomino** [comment]
![image](https://cloud.githubusercontent.com/assets/1450270/9701095/b79281b4-53e0-11e5-9874-d46c41fe74d4.png)

**Comment by jerone** [comment]
Do you have the [tool-bar](https://atom.io/packages/tool-bar) package installed?

**Comment by nbpalomino** [comment]
Hello, I recently installed and now works great.

Maybe must be an explicit dependency showed in package site.
