### ISSUE TITLE
Highlight the current parent folder

### ISSUE THREAD

**Issue by labo-css** [suda/toolbar-main#9]
Hi, in the picture here : https://atom.io/packages/tool-bar-main
I see the parent folder of the selected file is colored, how is this done? A theme? This plugin? Another thing i forgot?

Thanx, i'm failing to understand how it can be done.

**Comment by jerone** [comment]
This happens when you make a source control change.

**Comment by labo-css** [comment]
Oh.. thanx, i searched for that for hours without ever testing git with atom. My bad.

**Comment by jerone** [comment]
If you've got questions/issues/enhancements not related to this package you can use https://discuss.atom.io/
